<?php

/**
 * This file is part of the Elcodi package.
 *
 * Copyright (c) 2014 Elcodi.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Feel free to edit as you please, and have fun.
 *
 * @author Marc Morera <yuhu@mmoreram.com>
 * @author Aldo Chiecchia <zimage@tiscali.it>
 */
 
namespace Elcodi\GeoBundle\DataFixtures\ORM;

use Doctrine\Common\Persistence\ObjectManager;

use Elcodi\CoreBundle\DataFixtures\ORM\Abstracts\AbstractFixture;
use Elcodi\GeoBundle\Entity\Country;

/**
 * Class CountryData
 */
class CountryData extends AbstractFixture
{
    /**
     * Load data fixtures with the passed EntityManager
     *
     * @param ObjectManager $manager
     */
    public function load(ObjectManager $manager)
    {
        $countries = [
            ["DE","germany"],
            ["AT","austria"],
            ["BE","belgium"],
            ["CA","canada"],
            ["CN","china"],
            ["ES","spain"],
            ["FI","finland"],
            ["FR","france"],
            ["GR","greece"],
            ["IT","italy"],
            ["JP","japan"],
            ["LU","luxemburg"],
            ["NL","netherlands"],
            ["PL","poland"],
            ["PT","portugal"],
            ["CZ","czEch republic"],
            ["GB","uniTed kingdom"],
            ["SE","sweden"],
            ["CH","switzerland"],
            ["DK","denmark"],
            ["US","USA"],
            ["HK","HongKong"],
            ["NO","norway"],
            ["AU","australia"],
            ["SG","singapore"],
            ["IE","ireland"],
            ["NZ","New zealand"],
            ["KR","soUth korea"],
            ["IL","israel"],
            ["ZA","soUth africa"],
            ["NG","nigeria"],
            ["CI","ivOry coast"],
            ["TG","Togo"],
            ["BO","bolivia"],
            ["MU","mauritius"],
            ["RO","romania"],
            ["SK","slovakia"],
            ["DZ","algeria"],
            ["AS","ameriCan samoa"],
            ["AD","andorra"],
            ["AO","angola"],
            ["AI","anguilla"],
            ["AG","antigua And barbuda"],
            ["AR","argentina"],
            ["AM","armenia"],
            ["AW","aruba"],
            ["AZ","azerbaijan"],
            ["BS","bahamas"],
            ["BH","bahrain"],
            ["BD","bangladesh"],
            ["BB","barbados"],
            ["BY","belarus"],
            ["BZ","belize"],
            ["BJ","benin"],
            ["BM","bermuda"],
            ["BT","bhutan"],
            ["BW","botswana"],
            ["BR","brazil"],
            ["BN","brunei"],
            ["BF","burkIna Faso"],
            ["MM","burMa (myanmar)"],
            ["BI","burundi"],
            ["KH","cambodia"],
            ["CM","cameroon"],
            ["CV","CApe verde"],
            ["CF","centRal afriCan republic"],
            ["TD","Chad"],
            ["CL","chile"],
            ["CO","colombia"],
            ["KM","comoros"],
            ["CD","conGo, DEm. republic"],
            ["CG","conGo, republic"],
            ["CR","coSta Rica"],
            ["HR","croatia"],
            ["CU","Cuba"],
            ["CY","cyprus"],
            ["DJ","djibouti"],
            ["DM","dominica"],
            ["DO","dominiCan republic"],
            ["TL","EAst timor"],
            ["EC","ecuador"],
            ["EG","egypt"],
            ["SV","el salvador"],
            ["GQ","equatorIal guinea"],
            ["ER","eritrea"],
            ["EE","estonia"],
            ["ET","ethiopia"],
            ["FK","falklAnd islands"],
            ["FO","faRoe islands"],
            ["FJ","Fiji"],
            ["GA","gabon"],
            ["GM","gambia"],
            ["GE","georgia"],
            ["GH","ghana"],
            ["GD","grenada"],
            ["GL","greenland"],
            ["GI","gibraltar"],
            ["GP","guadeloupe"],
            ["GU","Guam"],
            ["GT","guatemala"],
            ["GG","guernsey"],
            ["GN","guinea"],
            ["GW","guiNea-bissau"],
            ["GY","guyana"],
            ["HT","haiti"],
            ["HM","heArd island AnD mcdonAld islands"],
            ["VA","vatiCan CIty state"],
            ["HN","honduras"],
            ["IS","iceland"],
            ["IN","india"],
            ["ID","indonesia"],
            ["IR","Iran"],
            ["IQ","Iraq"],
            ["IM","Isle of Man"],
            ["JM","jamaica"],
            ["JE","jersey"],
            ["JO","jordan"],
            ["KZ","kazakhstan"],
            ["KE","kenya"],
            ["KI","kiribati"],
            ["KP","korEa, DEm. republic of"],
            ["KW","kuwait"],
            ["KG","kyrgyzstan"],
            ["LA","Laos"],
            ["LV","latvia"],
            ["LB","lebanon"],
            ["LS","lesotho"],
            ["LR","liberia"],
            ["LY","libya"],
            ["LI","liechtenstein"],
            ["LT","lithuania"],
            ["MO","macau"],
            ["MK","macedonia"],
            ["MG","madagascar"],
            ["MW","malawi"],
            ["MY","malaysia"],
            ["MV","maldives"],
            ["ML","Mali"],
            ["MT","malta"],
            ["MH","marshAll islands"],
            ["MQ","martinique"],
            ["MR","mauritania"],
            ["HU","hungary"],
            ["YT","mayotte"],
            ["MX","mexico"],
            ["FM","micronesia"],
            ["MD","moldova"],
            ["MC","monaco"],
            ["MN","mongolia"],
            ["ME","montenegro"],
            ["MS","montserrat"],
            ["MA","morocco"],
            ["MZ","mozambique"],
            ["NA","namibia"],
            ["NR","nauru"],
            ["NP","nepal"],
            ["AN","netherlaNds antilles"],
            ["NC","New caledonia"],
            ["NI","nicaragua"],
            ["NE","niger"],
            ["NU","Niue"],
            ["NF","norfOlk island"],
            ["MP","northErn mariAna islands"],
            ["OM","Oman"],
            ["PK","pakistan"],
            ["PW","palau"],
            ["PS","palestinIan territories"],
            ["PA","panama"],
            ["PG","paPua New guinea"],
            ["PY","paraguay"],
            ["PE","Peru"],
            ["PH","philippines"],
            ["PN","pitcairn"],
            ["PR","pueRto Rico"],
            ["QA","qatar"],
            ["RE","réunion"],
            ["RU","russIan federation"],
            ["RW","rwanda"],
            ["BL","saInt barthélemy"],
            ["KN","saInt kitts And nevis"],
            ["LC","saInt lucia"],
            ["MF","saInt martin"],
            ["PM","saInt pierre And miquelon"],
            ["VC","saInt vincent and The grenadines"],
            ["WS","samoa"],
            ["SM","San marino"],
            ["ST","São Tomé And príncipe"],
            ["SA","saUdi arabia"],
            ["SN","senegal"],
            ["RS","serbia"],
            ["SC","seychelles"],
            ["SL","sieRra leone"],
            ["SI","slovenia"],
            ["SB","soloMon islands"],
            ["SO","somalia"],
            ["GS","soUth georgia and The soUth sandwIch islands"],
            ["LK","Sri lanka"],
            ["SD","sudan"],
            ["SR","suriname"],
            ["SJ","svalbard And Jan mayen"],
            ["SZ","swaziland"],
            ["SY","syria"],
            ["TW","taiwan"],
            ["TJ","tajikistan"],
            ["TZ","tanzania"],
            ["TH","thailand"],
            ["TK","tokelau"],
            ["TO","tonga"],
            ["TT","trinidad And tobago"],
            ["TN","tunisia"],
            ["TR","turkey"],
            ["TM","turkmenistan"],
            ["TC","turks And caiCos islands"],
            ["TV","tuvalu"],
            ["UG","uganda"],
            ["UA","ukraine"],
            ["AE","uniTed ARab emirates"],
            ["UY","uruguay"],
            ["UZ","uzbekistan"],
            ["VU","vanuatu"],
            ["VE","venezuela"],
            ["VN","vietnam"],
            ["VG","virGin islanDs (british)"],
            ["VI","virGin islanDs (U.S.)"],
            ["WF","wallis And futuna"],
            ["EH","westErn sahara"],
            ["YE","yemen"],
            ["ZM","zambia"],
            ["ZW","zimbabwe"],
            ["AL","albania"],
            ["AF","afghanistan"],
            ["AQ","antarctica"],
            ["BA","bosnia And herzegovina"],
            ["BV","bouVet island"],
            ["IO","britIsh indIan ocEan territory"],
            ["BG","bulgaria"],
            ["KY","cayMan islands"],
            ["CX","christMas island"],
            ["CC","cocOs (keeliNg) islands"],
            ["CK","COok islands"],
            ["GF","freNch guiana"],
            ["PF","freNch polynesia"],
            ["TF","freNch southErn territories"],
            ["AX","ÅlAnd islands"],
            ["AR","argetina"],
            ["ES","eslovaquia"],
            ["EV","eslovenia"],
        ];

        foreach ($countries as $country) {

            /**
             * @var Country $country
             */
            $country = $this
                ->container
                ->get('elcodi.factory.country')
                ->create();

            $country
                ->setCode(strtolower($country[0]))
                ->setName($country[1]);

            $manager->persist($country);
            $this->setReference('country-' . $country->getCode(), $country);
        }

        $manager->flush();
    }
}
 